sudo: false
language: python

env:
  global:
    - TWINE_USERNAME="anthrotype"
    - secure: DEXaN1oWE5N40eLec59MjYHQTFCj9yQn6rfCrtIPRmqkaOXCZCoaHvvefISvlA6TtloHOlyr7Kn7UU4RN5UUwCfj/IEmDyqyzy8FRtVeTpqP5BLkhzzuK30EPp0Ek+PKXPlqwR13MznQVRT4gZYhLah+3Vf1LoGSWPcmtKGV9y6BxyzaXuZUUhClCt03ED6OYA5ns6O3Odxy88x7+M+VGJk1k1C8F5OAh5bS63VnWoEAMveSzg6NczAPn1FTCpMdVA7Hfb8DSEPFrDGrK51s+u/itJ+FBaCQ5yIaROHvFwFlAQumMPw+sCiwlctXA7F9I6WGJEG7lUKSi9bQ3hJTGuOk7pWxdQfXd0QfGS6i/7/XmTAOSg37mJ/w+1jW87NzEoPKnd2zJIJYhfqLeAWq36o22R1FcYo1/71epeQRUjdXpFBLBqZDbdGRbZ3bQtTUuiYgIv46lBklPCFmV6iI71npYO0qgFXVfHitPE9Lhk1VjjgH3IxRbk9TrvJMgZFstBfOmORvbtCMz1Vxdlc0rVKkoQ7rOyT4oFqOZPrrGJglqiBad3QBAWCc5dN31CNmJGkMe99uADY5s8QXkXfJ29k/t1Getj2C6RZZzpBQ1d62IQ0yWqLiDYRN106nR0KNGU0RqdH8sUN3H6Domti4z2Cj0ESxLPAhGXJyuCI8Hy8=

branches:
  only:
    - master
    - /^v\d+\.\d+.*$/

matrix:
  include:
    - python: 3.6
      env: TOXENV=lint
    - python: 2.7
    - python: 3.6

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

install: pip install tox-travis

script:
  - tox

after_success:
  - |
    if [[ $TOXENV != lint ]]; then
        if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "googlefonts/glyphsLib" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then
            pip install --upgrade twine pip setuptools wheel
            python setup.py sdist
            pip wheel --no-deps --wheel-dir dist .
            twine upload dist/*.whl dist/*.zip
        else
            tox -e codecov
        fi
    fi
