[tool.black]
target-version = ["py36"]

[tool.setuptools_scm]
write_to = "Lib/glyphsLib/_version.py"

[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"
